In [77]:
import pandas as pd

In [78]:
cols = ['NO', 'SUB' , 'YEAR', 'FOREST_COVER', 'PCP', 'SNOWMELT', 'PET', 'ET', 'SoilWater', 'Perc', 'SurfQ', 'GW_Q', 'WaterYLD', 'SedYLD', 'OrgN', 'OrgP', 'NO3_SURQ','SolP', 'SedP', 'LatQ','LatQ_NO3', 'GWNO3', 'CHOLA', 'CBODU', 'DOXQ', 'TileNO3', 'QTile', 'TVAP']
print(len(cols[5:])) # 23 predictands.

23

In [79]:
# Read the original results from the SWAT model.
df = pd.read_table('regression_sub.txt',
                   header=None,
                   delim_whitespace=True,
                   names=cols)
print(df.shape) 
pd.set_option('display.max_columns', 500)
print(df.describe())

(10571, 28)
                 NO           SUB          YEAR  FOREST_COVER           PCP  \
count  10571.000000  10571.000000  10571.000000  10571.000000  10571.000000
mean       6.000000     16.000000   1996.000000     26.976906    990.438895
std        3.162427      8.944695      8.944695     19.262470    121.843264
min        1.000000      1.000000   1981.000000      1.426000    756.299000
25%        3.000000      8.000000   1988.000000     12.083000    900.500000
50%        6.000000     16.000000   1996.000000     22.273000    956.300000
75%        9.000000     24.000000   2004.000000     37.149000   1071.400000
max       11.000000     31.000000   2011.000000    125.524000   1674.512000

           SNOWMELT           PET            ET     SoilWater          Perc  \
count  10571.000000  10571.000000  10571.000000  10571.000000  10571.000000
mean     210.956231    720.851427    503.588852    128.195076    163.936871
std       60.985064     74.223560     52.726625     24.630394     70.401149
min       77.342000    512.171000    366.102000     71.867000     24.716000
25%      169.748000    672.433000    466.805000    109.457500    108.528500
50%      218.350000    718.612000    502.234000    126.947000    158.282000
75%      253.894000    775.156000    540.461000    145.856500    209.137500
max      342.777000   1063.838000    742.152000    190.530000    487.132000

              SurfQ     GW_Q      WaterYLD        SedYLD          OrgN  \
count  10571.000000  10571.0  10571.000000  10571.000000  10571.000000
mean     277.299162      0.0    438.249214      2.104754      5.261749
std       67.100214      0.0     72.746723      1.053597      2.270510
min       94.983000      0.0    268.129000      0.234000      1.738000
25%      230.127000      0.0    383.699500      1.352000      3.917500
50%      274.992000      0.0    434.347000      1.896000      4.791000
75%      323.460000      0.0    487.530000      2.622500      5.972000
max      516.427000      0.0    648.908000      9.920000     30.073000

               OrgP      NO3_SURQ          SolP          SedP          LatQ  \
count  10571.000000  10571.000000  10571.000000  10571.000000  10571.000000
mean       0.389043      1.662317      0.069837      0.159856      2.416820
std        0.182506      0.892859      0.032094      0.076600      1.123573
min        0.117000      0.016000      0.008000      0.013000      0.661000
25%        0.283000      1.025000      0.046000      0.103000      1.773000
50%        0.353000      1.507000      0.063000      0.147000      2.194000
75%        0.445000      2.143000      0.088000      0.203000      2.764000
max        2.410000      8.660000      0.240000      0.614000     11.925000

           LatQ_NO3    GWNO3    CHOLA    CBODU     DOXQ       TileNO3  \
count  10571.000000  10571.0  10571.0  10571.0  10571.0  10571.000000
mean       0.022313      0.0      0.0      0.0      0.0      0.334624
std        0.012853      0.0      0.0      0.0      0.0      0.625470
min        0.001000      0.0      0.0      0.0      0.0      0.000000
25%        0.013000      0.0      0.0      0.0      0.0      0.031200
50%        0.019000      0.0      0.0      0.0      0.0      0.116000
75%        0.029000      0.0      0.0      0.0      0.0      0.376000
max        0.087000      0.0      0.0      0.0      0.0      7.370000

              QTile          TVAP
count  10571.000000  10571.000000
mean      11.674861     31.084185
std       12.846002     32.960772
min        0.000000      0.000000
25%        2.500000      6.970000
50%        7.380000     19.500000
75%       17.000000     44.450000
max      104.000000    192.000000

In [85]:
df_obs = df_obs_raw[df_obs_raw['STATION'] == 18207002002]
#df_obs_NNOTUR = df_obs[df_obs['PARAMETER'] == 'NITRATES TOTAL,   UNFIL.REAC']

In [80]:
#df['NO']

In [81]:
df_obs_raw = pd.read_csv('data/PWQMN_1964-1999/PWQMN_1964-1999.csv')

In [82]:
#df_obs_raw[df_obs_raw['STATION'] == 18207002002]

In [83]:
len(df_obs_raw.PARAMETER.unique()), len(df_obs_raw.PARAM_CODE.unique())

(56, 55)

In [84]:
df_obs_raw.PARAMETER.unique()

array(['AMMONIUM, TOTAL   FILTER.REAC', 'AMMONIUM, TOTAL   UNFIL.REAC',
       'NITRITE,  FILTERED REACTIVE', 'NITRITE,  UNFILTERED REACTIVE',
       'NITRATE,  FILTERED REACTIVE', 'TURBIDITY',
       'NITRATES TOTAL,   FILTER.REAC', 'NITRATES TOTAL,   UNFIL.REAC',
       'NITROGEN,TOT,KJELDAHL/UNF.REA', 'PHOSPHATE,FILTERED REACTIVE',
       'PHOSPHORUS,UNFILTERED TOTAL', 'RESIDUE,PARTICULATE',
       'SILICATES,UNFILTERED REACTIVE', 'MANGANESE,UNFILTERED TOTAL',
       'SULPHATE, UNFILTERED REACTIVE', 'CARBON, DISSOLVED INORGANIC',
       'NICKEL,   UNFILTERED TOTAL', 'STRONTIUM, UNFILTERED TOTAL',
       'TITANIUM,  UNFILTERED TOTAL', 'CHROMIUM, UNFILTERED TOTAL',
       'CHROMI UM, UNFILTERED TOTAL', 'CONDUCTIVITY, 25C',
       'CONDUCTIVITY, AMBIENT', 'PH FIELD', 'HARDNESS,   TOTAL',
       'MAGNESIUM,UNFILTERED TOTAL', 'MERCURY,  UNFILTERED TOTAL',
       'MOLYBDENUM,UNFILTERED TOTAL', 'POTASSIUM,UNFILTERED TOTAL',
       'SELENIUM, UNFILTERED TOTAL', 'SODIUM,   UNFILTERED TOTAL',
       'VANADIUM,  UNFILTERED TOTAL', 'COPPER,   UNFILTERED TOTAL',
       'DISSOLVED OXYGEN', 'STREAM CONDITION', 'TEMPERATURE, WATER',
       'IRON,     UNFILTERED TOTAL', 'RESIDUE,FILTERED',
       'LEAD,     UNFILTERED TOTAL', 'PH (-LOG H+ CONCN)',
       'ZINC,  UNFILTERED TOTAL', 'RESIDUE,TOTAL',
       'ALUMINIUM, UNFILTERED TOTAL', 'BERYLIUM,UNFILTERED TOTAL',
       'CHEMICAL OXYGEN DEMAND', 'CALCIUM, UNFILTERED TOTAL',
       'ALKALINITY, TOTAL', 'ARSENIC,    UNFILTERED TOTAL',
       'BARIUM,  UNFILTERED TOTAL', 'BOD,  5 DAY,  TOTAL DEMAND',
       'CADMIUM, UNFILTERED TOTAL', 'CHLOROPHYLL-B, TOTAL',
       'CHLOROPHYLL-A, TOTAL', 'CHLORIDE,         UNFIL.REAC',
       'COBALT,   UNFILTERED TOTAL', 'CARBON, DISSOLVED ORGANIC'], dtype=object)

In [86]:
#df_obs

In [87]:
df_obs.describe()

            STATION         TIME  RESULT_VALUE
count  7.189000e+03  7189.000000   7189.000000
mean   1.820700e+10  1183.466963     47.983899
std    0.000000e+00   332.170251    141.599323
min    1.820700e+10     0.000000     -6.490000
25%    1.820700e+10  1005.000000      0.050000
50%    1.820700e+10  1140.000000      2.000000
75%    1.820700e+10  1310.000000     20.700000
max    1.820700e+10  2410.000000   6040.000000

In [88]:
# Drop columns we won't use for analyses.
# TODO: double-check UNITS matches SWAT.
df_obs = df_obs.drop(['VALUE_QUALIFIER','REMARK_CODE1', 'REMARK_CODE', 'REMARK_CODE', 'ANAL_METH', 'UNITS'], axis=1)

In [89]:
# Remove the extra timestamp at the end of the date.
df_obs['DATE'] = df_obs['DATE'].apply(lambda s: s.split(' ')[0])

In [90]:
#df_obs

In [91]:
obs_nnotur = df_obs[df_obs['PARAMETER'] == 'NITRATES TOTAL,   UNFIL.REAC']
#obs_nnotur

In [92]:
# Looks like we only have 1994-1999.
d_obs = {}
for i,r in obs_nnotur.iterrows():
    try:
        year = r['DATE'].split('-')[0]
    except:
        print(year)
    if year in d_obs:
        d_obs[year].append(r['RESULT_VALUE'])
    else:
        d_obs[year] = [r['RESULT_VALUE']]
print d_obs

{'1995': [2.27, 2.02, 0.42], '1994': [0.56, 0.285, 1.34, 1.51], '1997': [1.63, 0.53, 0.15, 0.19, 0.005, 0.135, 0.36, 1.89], '1996': [1.84, 1.56, 1.33, 0.24, 1.37, 0.54, 2.21, 2.8, 2.27], '1999': [0.785, 4.0, 1.78, 0.185, 0.521, 2.55, 2.3], '1998': [1.24, 0.39, 2.75, 1.74, 0.71, 1.16, 1.77, 1.02]}

In [93]:
#df['NO3_SURQ']

In [94]:
# 10 measures ('NO') per year.
# Loop by subbasins.
d = {}
for i in range(1,32):
    #dx = {yr:[] for yr in dp['YEAR'].unique()}
    dx = {}
    # Isolate the years we have observations for && loop by subbasin.
    dp = df[['NO','SUB','YEAR','FOREST_COVER', 'PCP','NO3_SURQ']][(df['SUB'] == i) & (df['YEAR'] <= 1999) & (1994 <= df['YEAR'])]
    #print(dp)
    for year in dp['YEAR'].unique():
        # Group different "NO"s together by year.
        ds = dp[(dp['YEAR']==year) & (dp['SUB']==i)]
        #print(ds)
        #print('cat')
        if ds.empty:
            print('ERROR: Year {0}, Basin {1}'.format(year,i))
            print(dp)
        dx[year] = ds
    d[i] = dx

In [95]:
import numpy as np
from scipy import stats

# So forest cover doesn't really change between years.
# And some basin share values.
for basin in d:
    predictors = d[basin]
    forest = []
    pcp = []
    #print(predictors)
    for year in predictors:
        x = predictors[year]
        # This is probably a bad idea.
        #print(basin,year,np.mean(x['FOREST_COVER']), np.mean(x['PCP']))
        forest.append(np.mean(x['FOREST_COVER']))
        pcp.append(np.mean(x['PCP']))
    #print(forest)
    #print(pcp)
    predictands = [np.mean(l) for l in d_obs.itervalues()]
    #print(predictands)
    f_rho, f_pval = stats.spearmanr(forest,predictands)
    p_rho, p_pval = stats.spearmanr(pcp,predictands)
    print('f_rho: {0}, f_pval: {1}, p_rho: {2}, p_val: {3}, basin: {4}'.format(f_rho,f_pval,p_rho,p_pval,basin))

f_rho: nan, f_pval: nan, p_rho: -0.371428571429, p_val: 0.468478134111, basin: 1
f_rho: nan, f_pval: nan, p_rho: -0.371428571429, p_val: 0.468478134111, basin: 2
f_rho: nan, f_pval: nan, p_rho: -0.371428571429, p_val: 0.468478134111, basin: 3
f_rho: nan, f_pval: nan, p_rho: -0.371428571429, p_val: 0.468478134111, basin: 4
f_rho: nan, f_pval: nan, p_rho: -0.371428571429, p_val: 0.468478134111, basin: 5
f_rho: nan, f_pval: nan, p_rho: -0.371428571429, p_val: 0.468478134111, basin: 6
f_rho: nan, f_pval: nan, p_rho: -0.371428571429, p_val: 0.468478134111, basin: 7
f_rho: nan, f_pval: nan, p_rho: -0.371428571429, p_val: 0.468478134111, basin: 8
f_rho: nan, f_pval: nan, p_rho: -0.371428571429, p_val: 0.468478134111, basin: 9
f_rho: nan, f_pval: nan, p_rho: -0.885714285714, p_val: 0.0188454810496, basin: 10
f_rho: nan, f_pval: nan, p_rho: -0.371428571429, p_val: 0.468478134111, basin: 11
f_rho: nan, f_pval: nan, p_rho: -0.885714285714, p_val: 0.0188454810496, basin: 12
f_rho: nan, f_pval: nan, p_rho: -0.371428571429, p_val: 0.468478134111, basin: 13
f_rho: nan, f_pval: nan, p_rho: -0.371428571429, p_val: 0.468478134111, basin: 14
f_rho: nan, f_pval: nan, p_rho: -0.885714285714, p_val: 0.0188454810496, basin: 15
f_rho: nan, f_pval: nan, p_rho: -0.885714285714, p_val: 0.0188454810496, basin: 16
f_rho: nan, f_pval: nan, p_rho: -0.885714285714, p_val: 0.0188454810496, basin: 17
f_rho: nan, f_pval: nan, p_rho: -0.885714285714, p_val: 0.0188454810496, basin: 18
f_rho: nan, f_pval: nan, p_rho: -0.885714285714, p_val: 0.0188454810496, basin: 19
f_rho: nan, f_pval: nan, p_rho: -0.371428571429, p_val: 0.468478134111, basin: 20
f_rho: nan, f_pval: nan, p_rho: -0.885714285714, p_val: 0.0188454810496, basin: 21
f_rho: nan, f_pval: nan, p_rho: -0.371428571429, p_val: 0.468478134111, basin: 22
f_rho: nan, f_pval: nan, p_rho: -0.885714285714, p_val: 0.0188454810496, basin: 23
f_rho: nan, f_pval: nan, p_rho: -0.885714285714, p_val: 0.0188454810496, basin: 24
f_rho: nan, f_pval: nan, p_rho: -0.371428571429, p_val: 0.468478134111, basin: 25
f_rho: nan, f_pval: nan, p_rho: -0.142857142857, p_val: 0.787172011662, basin: 26
f_rho: nan, f_pval: nan, p_rho: -0.142857142857, p_val: 0.787172011662, basin: 27
f_rho: nan, f_pval: nan, p_rho: -0.142857142857, p_val: 0.787172011662, basin: 28
f_rho: nan, f_pval: nan, p_rho: -0.142857142857, p_val: 0.787172011662, basin: 29
f_rho: nan, f_pval: nan, p_rho: -0.142857142857, p_val: 0.787172011662, basin: 30
f_rho: nan, f_pval: nan, p_rho: -0.142857142857, p_val: 0.787172011662, basin: 31

In [96]:
predictands = [np.mean(l) for l in d_obs.itervalues()]
predictands

[1.5700000000000001,
 0.92375000000000007,
 0.61125000000000007,
 1.5733333333333333,
 1.7315714285714283,
 1.3475000000000001]

In [97]:
# Let's create a linear model based of basin 10.
predictors = d[10]
forest = []
pcp = []
no3_surq = []
for year in predictors:
    x = predictors[year]
    # This is probably a bad idea, but we need 1 value per year.
    forest.append(np.mean(x['FOREST_COVER']))
    pcp.append(np.mean(x['PCP']))
    no3_surq.append(np.mean(x['NO3_SURQ']))

In [98]:
df = pd.DataFrame({'forest':forest,'pcp':pcp})

In [99]:
df

      forest          pcp
0  49.740182   966.400091
1  49.740182  1158.600091
2  49.740182  1120.900273
3  49.740182   942.700000
4  49.740182   920.200000
5  49.740182   945.000000

In [100]:
from sklearn.cross_validation import KFold
from sklearn import linear_model

# Now let's compute RMSE using 5-fold x-validation
kf = KFold(len(no3_surq), n_folds=5)
xval_err = 0
for train,test in kf:
    #print(train,test)
    X = df[df.index.isin(train)]
    y = [no3_surq[i] for i in train]
    # Create linear regression object# Create
    lm = linear_model.LinearRegression()
    model = lm.fit(X,y)
    p = model.predict(df[df.index.isin(test)])
    e = p-[no3_surq[i] for i in test]
    #print(p,e)
    xval_err += np.dot(e,e)
    
rmse_5cv = np.sqrt(xval_err/len(no3_surq))

In [101]:
method_name = 'Simple Linear Regression'
print('Method: %s' %method_name)
print('RMSE on 5-fold CV: %.4f' %rmse_5cv)

Method: Simple Linear Regression
RMSE on 5-fold CV: 1.4354

In [102]:
df.values.shape

(6, 2)

In [103]:
from sklearn.model_selection import cross_val_score
# It might help to shuffle the X,y for fitting a linear regression.
scores = cross_val_score(linear_model.LinearRegression(), df.values, predictands, cv=5)

In [104]:
print(scores)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

[-0.44610869  0.          0.          0.          0.        ]
Accuracy: -0.09 (+/- 0.36)

In [105]:
from sklearn.ensemble import RandomForestRegressor
scores = cross_val_score(RandomForestRegressor(), df.values, predictands, cv=5)

In [106]:
print(scores)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

[ 0.83487911  0.          0.          0.          0.        ]
Accuracy: 0.17 (+/- 0.67)

In [107]:
# Let's include all the basins.
no3_surq = []
forest = []
pcp = []
basins = []
for basin in d:
    predictors = d[basin]
    for year in predictors:
        x = predictors[year]
        # This is probably a bad idea, but we need 1 value per year.
        forest.append(np.mean(x['FOREST_COVER']))
        pcp.append(np.mean(x['PCP']))
        no3_surq.append(np.mean(x['NO3_SURQ']))
        basins.append(basin)

In [108]:
df = pd.DataFrame({'forest':forest,'pcp':pcp, 'basin':basins})

In [118]:
df

     basin     forest          pcp
0        1  21.885636   946.000000
1        1  21.885636  1056.700000
2        1  21.885636  1171.399909
3        1  21.885636   904.200000
4        1  21.885636  1082.699909
5        1  21.885636  1071.799909
6        2  25.624364   946.000182
7        2  25.624364  1056.700182
8        2  25.624364  1171.400727
9        2  25.624364   904.200455
10       2  25.624364  1082.700273
11       2  25.624364  1071.800455
12       3  39.635182   945.999909
13       3  39.635182  1056.699818
14       3  39.635182  1171.399636
15       3  39.635182   904.199818
16       3  39.635182  1082.699727
17       3  39.635182  1071.799727
18       4  25.282455   945.999727
19       4  25.282455  1056.699727
20       4  25.282455  1171.399727
21       4  25.282455   904.199818
22       4  25.282455  1082.699727
23       4  25.282455  1071.799727
24       5  46.156455   946.000182
25       5  46.156455  1056.700182
26       5  46.156455  1171.400182
27       5  46.156455   904.200182
28       5  46.156455  1082.700182
29       5  46.156455  1071.800273
..     ...        ...          ...
156     27  36.154727   866.700364
157     27  36.154727   932.500273
158     27  36.154727  1166.000455
159     27  36.154727   948.400364
160     27  36.154727  1025.600364
161     27  36.154727   948.700364
162     28  19.144000   866.699455
163     28  19.144000   932.499455
164     28  19.144000  1165.999364
165     28  19.144000   948.399455
166     28  19.144000  1025.599273
167     28  19.144000   948.699455
168     29  34.556182   866.700364
169     29  34.556182   932.500091
170     29  34.556182  1166.000545
171     29  34.556182   948.400545
172     29  34.556182  1025.600545
173     29  34.556182   948.700364
174     30  48.358909   866.700182
175     30  48.358909   932.500182
176     30  48.358909  1166.000091
177     30  48.358909   948.400273
178     30  48.358909  1025.600182
179     30  48.358909   948.700182
180     31  45.663909   866.699636
181     31  45.663909   932.499636
182     31  45.663909  1165.999636
183     31  45.663909   948.399636
184     31  45.663909  1025.599636
185     31  45.663909   948.699727

[186 rows x 3 columns]

In [111]:
print(len(df.values))
l = []
for i in range(31):
    l += predictands
print(len(l))

186
186

In [112]:
scores = cross_val_score(RandomForestRegressor(), df.values, l, cv=10)
print(scores)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

[ 0.9884599   0.09391105  0.99895903  0.99898687  0.99983514  0.99939549
  0.99637099  0.76109295  0.96529538  0.99416311]
Accuracy: 0.88 (+/- 0.54)

In [114]:
# Let's explore what the random forest is doing.
regr = RandomForestRegressor()
regr.fit(df.values, l)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [115]:
print(regr.feature_importances_)

[ 0.00761515  0.00523849  0.98714636]

In [116]:
# Let's doing some scaling before-hand.
from sklearn import preprocessing
from sklearn.pipeline import make_pipeline
rgr = make_pipeline(preprocessing.StandardScaler(), RandomForestRegressor())

In [117]:
# Still pretty bad.
scores = cross_val_score(rgr, df.values, l, cv=10)
print(scores)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

[ 0.99777127  0.12356912  0.99910477  0.99779355  0.99927455  0.99904432
  0.99899523  0.76293736  0.97101343  0.99037953]
Accuracy: 0.88 (+/- 0.53)

In [129]:
d_forests = {'forest{0}'.format(basin):forest[basin-1:basin+5]
     for basin in range(1,32)}
d_pcps = {'pcp{0}'.format(basin):pcp[basin-1:basin+5]
     for basin in range(1,32)}
d_forests.update(d_pcps)
joined = d_forests
df = pd.DataFrame(joined)

In [130]:
df

,forest1,forest10,forest11,forest12,forest13,forest14,forest15,forest16,forest17,forest18,forest19,forest2,forest20,forest21,forest22,forest23,forest24,forest25,forest26,forest27,forest28,forest29,forest3,forest30,forest31,forest4,forest5,forest6,forest7,forest8,forest9,pcp1,pcp10,pcp11,pcp12,pcp13,pcp14,pcp15,pcp16,pcp17,pcp18,pcp19,pcp2,pcp20,pcp21,pcp22,pcp23,pcp24,pcp25,pcp26,pcp27,pcp28,pcp29,pcp3,pcp30,pcp31,pcp4,pcp5,pcp6,pcp7,pcp8,pcp9
0,21.885636,25.624364,25.624364,25.624364,39.635182,39.635182,39.635182,39.635182,39.635182,39.635182,25.282455,21.885636,25.282455,25.282455,25.282455,25.282455,25.282455,46.156455,46.156455,46.156455,46.156455,46.156455,21.885636,46.156455,70.961545,21.885636,21.885636,21.885636,25.624364,25.624364,25.624364,946.000000,904.200455,1082.700273,1071.800455,945.999909,1056.699818,1171.399636,904.199818,1082.699727,1071.799727,945.999727,1056.700000,1056.699727,1171.399727,904.199818,1082.699727,1071.799727,946.000182,1056.700182,1171.400182,904.200182,1082.700182,1171.399909,1071.800273,973.722455,904.200000,1082.699909,1071.799909,946.000182,1056.700182,1171.400727
1,21.885636,25.624364,25.624364,39.635182,39.635182,39.635182,39.635182,39.635182,39.635182,25.282455,25.282455,21.885636,25.282455,25.282455,25.282455,25.282455,46.156455,46.156455,46.156455,46.156455,46.156455,46.156455,21.885636,70.961545,70.961545,21.885636,21.885636,25.624364,25.624364,25.624364,25.624364,1056.700000,1082.700273,1071.800455,945.999909,1056.699818,1171.399636,904.199818,1082.699727,1071.799727,945.999727,1056.699727,1171.399909,1171.399727,904.199818,1082.699727,1071.799727,946.000182,1056.700182,1171.400182,904.200182,1082.700182,1071.800273,904.200000,973.722455,1087.666545,1082.699909,1071.799909,946.000182,1056.700182,1171.400727,904.200455
2,21.885636,25.624364,39.635182,39.635182,39.635182,39.635182,39.635182,39.635182,25.282455,25.282455,25.282455,21.885636,25.282455,25.282455,25.282455,46.156455,46.156455,46.156455,46.156455,46.156455,46.156455,70.961545,21.885636,70.961545,70.961545,21.885636,25.624364,25.624364,25.624364,25.624364,25.624364,1171.399909,1071.800455,945.999909,1056.699818,1171.399636,904.199818,1082.699727,1071.799727,945.999727,1056.699727,1171.399727,904.200000,904.199818,1082.699727,1071.799727,946.000182,1056.700182,1171.400182,904.200182,1082.700182,1071.800273,973.722455,1082.699909,1087.666545,1205.727818,1071.799909,946.000182,1056.700182,1171.400727,904.200455,1082.700273
3,21.885636,39.635182,39.635182,39.635182,39.635182,39.635182,39.635182,25.282455,25.282455,25.282455,25.282455,21.885636,25.282455,25.282455,46.156455,46.156455,46.156455,46.156455,46.156455,46.156455,70.961545,70.961545,21.885636,70.961545,70.961545,25.624364,25.624364,25.624364,25.624364,25.624364,25.624364,904.200000,945.999909,1056.699818,1171.399636,904.199818,1082.699727,1071.799727,945.999727,1056.699727,1171.399727,904.199818,1082.699909,1082.699727,1071.799727,946.000182,1056.700182,1171.400182,904.200182,1082.700182,1071.800273,973.722455,1087.666545,1071.799909,1205.727818,930.697545,946.000182,1056.700182,1171.400727,904.200455,1082.700273,1071.800455
4,21.885636,39.635182,39.635182,39.635182,39.635182,39.635182,25.282455,25.282455,25.282455,25.282455,25.282455,21.885636,25.282455,46.156455,46.156455,46.156455,46.156455,46.156455,46.156455,70.961545,70.961545,70.961545,25.624364,70.961545,70.961545,25.624364,25.624364,25.624364,25.624364,25.624364,39.635182,1082.699909,1056.699818,1171.399636,904.199818,1082.699727,1071.799727,945.999727,1056.699727,1171.399727,904.199818,1082.699727,1071.799909,1071.799727,946.000182,1056.700182,1171.400182,904.200182,1082.700182,1071.800273,973.722455,1087.666545,1205.727818,946.000182,930.697545,1114.428455,1056.700182,1171.400727,904.200455,1082.700273,1071.800455,945.999909
5,21.885636,39.635182,39.635182,39.635182,39.635182,25.282455,25.282455,25.282455,25.282455,25.282455,25.282455,25.624364,46.156455,46.156455,46.156455,46.156455,46.156455,46.156455,70.961545,70.961545,70.961545,70.961545,25.624364,70.961545,70.961545,25.624364,25.624364,25.624364,25.624364,39.635182,39.635182,1071.799909,1171.399636,904.199818,1082.699727,1071.799727,945.999727,1056.699727,1171.399727,904.199818,1082.699727,1071.799727,946.000182,946.000182,1056.700182,1171.400182,904.200182,1082.700182,1071.800273,973.722455,1087.666545,1205.727818,930.697545,1056.700182,1114.428455,1103.209091,1171.400727,904.200455,1082.700273,1071.800455,945.999909,1056.699818

In [147]:
# Let's explore what the random forest is doing.
regr = RandomForestRegressor()
regr.fit(df.values, predictands)
imps = regr.feature_importances_
list_tuples = []
for i,v in enumerate(imps):
    t = (i,v)
    print(t)
    if v >= 0.01:
        list_tuples.append(t)

(0, 0.0)
(1, 0.08744861942751167)
(2, 0.0)
(3, 0.0)
(4, 0.0)
(5, 0.0)
(6, 0.0)
(7, 0.0)
(8, 0.0)
(9, 0.0)
(10, 0.0)
(11, 0.0)
(12, 0.0)
(13, 0.0)
(14, 0.090294324910233301)
(15, 0.0)
(16, 0.0)
(17, 0.0)
(18, 0.007539818611517932)
(19, 0.0)
(20, 0.17605335440697917)
(21, 0.0)
(22, 0.0)
(23, 0.0)
(24, 0.0)
(25, 0.0)
(26, 0.0)
(27, 0.0)
(28, 0.0)
(29, 0.0)
(30, 0.0)
(31, 0.0)
(32, 0.095966184414756031)
(33, 0.0)
(34, 0.0)
(35, 0.11375603072494518)
(36, 0.0043060828932391885)
(37, 0.0)
(38, 0.0)
(39, 0.0)
(40, 0.0)
(41, 0.0)
(42, 0.11209786222452497)
(43, 0.0)
(44, 0.0)
(45, 9.0343196858912944e-07)
(46, 0.0082452976792491417)
(47, 0.092882499288251916)
(48, 0.0)
(49, 0.0)
(50, 0.0)
(51, 0.0)
(52, 0.0)
(53, 0.0)
(54, 0.0)
(55, 8.097212859826754e-07)
(56, 0.0)
(57, 0.015074327226937278)
(58, 0.18662820994883295)
(59, 0.0)
(60, 0.0)
(61, 0.0097056750897667014)

In [148]:
print(list_tuples)

[(1, 0.08744861942751167), (14, 0.090294324910233301), (20, 0.17605335440697917), (32, 0.095966184414756031), (35, 0.11375603072494518), (42, 0.11209786222452497), (47, 0.092882499288251916), (57, 0.015074327226937278), (58, 0.18662820994883295)]

In [149]:
df[df.columns[41]]

0     945.999727
1    1056.699727
2    1171.399727
3     904.199818
4    1082.699727
5    1071.799727
Name: pcp19, dtype: float64

In [150]:
df[df.columns[57]]

0    1082.699909
1    1071.799909
2     946.000182
3    1056.700182
4    1171.400727
5     904.200455
Name: pcp5, dtype: float64

In [151]:
for t in list_tuples:
    print(df[df.columns[t[0]]])

0    25.624364
1    25.624364
2    25.624364
3    39.635182
4    39.635182
5    39.635182
Name: forest10, dtype: float64
0    25.282455
1    25.282455
2    25.282455
3    46.156455
4    46.156455
5    46.156455
Name: forest22, dtype: float64
0    46.156455
1    46.156455
2    46.156455
3    70.961545
4    70.961545
5    70.961545
Name: forest28, dtype: float64
0     904.200455
1    1082.700273
2    1071.800455
3     945.999909
4    1056.699818
5    1171.399636
Name: pcp10, dtype: float64
0     945.999909
1    1056.699818
2    1171.399636
3     904.199818
4    1082.699727
5    1071.799727
Name: pcp13, dtype: float64
0    1056.700000
1    1171.399909
2     904.200000
3    1082.699909
4    1071.799909
5     946.000182
Name: pcp2, dtype: float64
0    1071.799727
1     946.000182
2    1056.700182
3    1171.400182
4     904.200182
5    1082.700182
Name: pcp24, dtype: float64
0    1082.699909
1    1071.799909
2     946.000182
3    1056.700182
4    1171.400727
5     904.200455
Name: pcp5, dtype: float64
0    1071.799909
1     946.000182
2    1056.700182
3    1171.400727
4     904.200455
5    1082.700273
Name: pcp6, dtype: float64

In [146]:
scores = cross_val_score(RandomForestRegressor(), df.values, predictands, cv=5)
print(scores)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

[-0.85134623  0.          0.          0.          0.        ]
Accuracy: -0.17 (+/- 0.68)